# Generated by Django 3.1.2 on 2020-11-16 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_lastupdated', models.DateTimeField(auto_now=True)),
                ('parent_categodry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('keywords', models.CharField(max_length=200, unique=True)),
                ('logo_url', models.EmailField(max_length=200, unique=True)),
                ('banner_url', models.CharField(max_length=200)),
                ('tittle', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=200)),
                ('instagram', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_lastupdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('url_photos', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.EmailField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('stock', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_lastupdated', models.DateTimeField(auto_now=True)),
                ('category_id', models.ManyToManyField(to='stores.Category')),
                ('store_id', models.ManyToManyField(to='stores.Store')),
            ],
        ),
    ]
