# Generated by Django 3.1.2 on 2020-11-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20201127_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='keywords',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='store',
            name='logo_url',
            field=models.SlugField(max_length=200),
        ),
    ]
