# Generated by Django 3.1.2 on 2020-11-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20201129_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_categodry_id',
            new_name='parent_category_id',
        ),
        migrations.RenameField(
            model_name='store',
            old_name='tittle',
            new_name='title',
        ),
    ]
